{% set name = "nx-parallel" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nx_parallel-{{ version }}.tar.gz
  sha256: f3b98323f9e160a15698d6471eee59eb90a0356b2da8a9ddd80818445afc0d04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - networkx
    - joblib

test:
  imports:
    - nx_parallel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/networkx/nx-parallel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: "A parallel backend for NetworkX"
  description: |
    A parallel backend for NetworkX. It uses joblib to run NetworkX algorithms
    on multiple CPU cores.
  doc_url: https://github.com/networkx/nx-parallel
  dev_url: https://github.com/networkx/nx-parallel

extra:
  recipe-maintainers:
    - MridulS
    - Schefflera-Arboricola
